### ISSUE TITLE
HTTP Error 503. Service Unavailable

### ISSUE THREAD

**Issue by tunjioye** [aminubakori/InterSwitchWebPay#1]
Trying out the code on localhost, an HTTP ERROR 503 shows up after clicking the Pay via Interswitch WebPay Button.
 
Service Unavailable
HTTP Error 503. The service is unavailable.

**Comment by aminubakori** [comment]
@Teejay1589 This library is no longer supported. 

You can instead try out Payant at https://payant.ng. 

Developer documentation at https://developers.payant.ng and libraries can be found at https://developers.payant.ng/overview/libraries. 

The PHP library is https://github.com/JonathanItakpe/payantNG-php. 

I hope this helps.
:)

**Comment by tunjioye** [comment]
Okay
Big Tanks
